name: jekyll-cd

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install
          bundle exec jekyll -v || exit 1

      - name: Clean site
        run: |
          if [ -d "docs" ]; then
            rm -rf docs/*
          fi

      - name: Build site
        run: |
          bundle exec jekyll build -d docs

      - name: Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git --no-pager show --color
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
